### ISSUE TITLE
Nexus 7 (2012) emulator does not behave as expected

### ISSUE THREAD

**Issue by argenkiwi** [FlutterRocks/adaptive-master-detail-layouts#1]
I created a Nexus 7 (2012) AVD with the default settings using Oreo (API 26). I can see the tablet layout in portrait mode and not in landscape mode (I would expect this to be the way around). Doing some debugging, `smallestDimension` seems to be different in landscape and portrait modes. I suspect the `constraints` used do not represent the size of the screen.

**Comment by roughike** [comment]
Should be fixed in latest master.
